/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.97.0
*/

export { UsdfTokenContract } from './UsdfTokenContract';
export { UsdfTokenContractFactory } from './UsdfTokenContractFactory';
